theme: jekyll-theme-minimal

title: Florencia Pucci

description: Bachelor graduate in economics at Universidad de Buenos Aires. Master in economics student at Universidad de San Andr√©s (thesis pending). 

logo: ![alt text](https://github.com/florenciapucci/florenciapucci/blob/florenciapucci/git.jpg?raw=true)

